#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This file is sourced from main.sh to update distro-specific defaults.
# It must set at least ARCH and MIRROR if not already specified.

if [ -z "$ARCH" ]; then
    ARCH="`uname -m | sed -e 's i.86 i686 ;s arm.* armv7h ;'`"
fi

if [ -z "$MIRROR" ]; then
    if [ "$ARCH" = 'x86_64' -o "$ARCH" = 'i686' ]; then
        MIRROR="${CROUTON_MIRROR_manjaro:-http://vm1.sorch.info/manjaro/\$rel/\$repo/\$arch}"
    fi
fi

if [ -z "$MIRROR2" ]; then
    if [ "$ARCH" = 'x86_64' -o "$ARCH" = 'i686' ]; then
        MIRROR2="${CROUTON_MIRROR_manjaro:-http://mirror.jmu.edu/manjaro/\$rel/\$repo/\$arch}"
    fi
fi

if [ "$RELEASE" = 'manjaro' ]; then
    BOOTSTRAP_RELEASE='stable'
    echo "The default repository for Manjaro is the stable branch.
You may want to change your repository at a later time.
The options for the branches are stable testing and unstable.
Here is a rough update schedule for Manjaro:
The stable branch get updates bi-weekly from Manjaro testing.
The testing branch get updates weekly from Manjaro unstable.
The unstable branch get daily updates from Arch stable.
Use the following commands when in the chroot to change what branch you
want to use:
sudo pacman-mirrors -g -b <branch>
sudo pacman -Syyu
Press Enter to continue the installation: "
read tmp
fi
