#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='core'
DESCRIPTION='Basic CLI tools such as ssh. For manjaro this will add base-devel git and yaourt'
HOSTBIN='startcli'
CHROOTBIN='croutonpowerd'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
install dbus arch=openssh,openssh-client kbd manjaro=git manjaro=yaourt


TIPS="$TIPS
You can start a shell in a new VT via the startcli host command: sudo startcli
"
