#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='gtk-extra'
DESCRIPTION='Installs the enlightenment desktop environment from aur-git. (Approx. 50MB)'
HOSTBIN='starte17 starte19'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:

  #Yaourt -S --noconfirm 


TIPS="$TIPS
You can start e19 via the starte17 host command: sudo starte17
"
