#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='x11'
DESCRIPTION='GTK-based tools including gdebi, gksu, a simple browser. The manjaro edition includes
firefox, geany and meld.'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
install arch=,gdebi arch=,gksu manjaro=firefox,arch=netsurf,netsurf-gtk manjaro=geany manjaro=meld
install manjaro=catfish manjaro=vlc manjaro=evince manjaro=clementine manjaro=galculator

if [ "${DISTROAKA:-"$DISTRO"}" = 'debian' ]; then
    # Add netsurf-gtk to Debian-alternatives if not already there
    netsurf='/usr/bin/netsurf-gtk'
    for link in x-www-browser gnome-www-browser; do
        if ! update-alternatives --query "$link" | grep -q "$netsurf"; then
            update-alternatives --install "/usr/bin/$link" "$link" "$netsurf" 10
        fi
    done
fi
# Arch: Alternative handling is done in x11-common
